# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast matrix multiplication using C++
#'
#' This function offers a faster matrix multiplication than R provides natively.
#' It takes two matrices, `A` and `B` and returns the matrix multiplication of
#' `A %*% B`.
#'
#' @param A left matrix in the multiplication
#' @param B right matrix in the multiplication
#'
#' @returns a matrix of size `nrow(A)` by `ncol(B)`
#' @export
#'
mat_mult <- function(A, B) {
    .Call(`_componentts_mat_mult`, A, B)
}

#' Randomize (permute) each column of a matrix
#'
#' The C++ implementation gives this function more speed than the `rand_each_col()`
#' function written in just in R.
#' This function randomizes or permutes a matrix by reordering the values in each
#' column of the matrix. This results in a matrix where the relationships (correlations)
#' within the matrix are broken, and when compared to another matrix with different
#' variables and the same participants, the relationships between the two matrices
#' are also now broken.
#'
#' This function is the option used when selecting "rand_each_col" in the stopping rule
#' functions such as [SRP()] or [DRP()].
#'
#' @param X the matrix to permute
#'
#' @returns a matrix with the values in each column of `X` reordered
#' @export
rand_each_col_cpp <- function(X) {
    .Call(`_componentts_rand_each_col_cpp`, X)
}

#' Randomize (permute) the rows of a matrix
#'
#' The C++ implementation gives this function more speed than the `rand_rows()`
#' function written in just in R.
#' This function randomizes or permutes a matrix by reordering complete rows of
#' the matrix. This results in a matrix where the relationships (correlations)
#' within the matrix are preserved. But when compared to another matrix with different
#' variables and the same participants, the relationships between the two matrices
#' are now broken.
#'
#' This function is the option used when selecting "rand_rows" in the stopping rule
#' functions such as [SRP()] or [DRP()].
#'
#' @param X the matrix to permute
#'
#' @returns a matrix with the rows of `X` reordered
#' @export
rand_rows_cpp <- function(X) {
    .Call(`_componentts_rand_rows_cpp`, X)
}

